sudo: required
services:
  - docker

before_script:
  - docker pull hackoregoncivic/backend-docker-django-dev || true

script:
  - docker-compose build

after_script:
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

deploy:
  provider: script
  script: bin/deploy.sh
