sudo: required
services:
  - docker
  - postgresql
addons:
  postgresql: "11.2"

before_script:
  - docker pull hackoregoncivic/backend-docker-django-dev || true
  - psql -c 'create database backend;' -U postgres

script:
  - docker-compose build
  - docker-compose up
  - docker ps | grep -q hackoregoncivic/backend-docker-django-dev

after_script:
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

deploy:
  provider: script
  script: bin/deploy.sh
